name: CB Secret PR Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  SecretScanning:
    uses: inaitech/cb-secrets-scanner/.github/workflows/cb-secret-scan.yml@main
    secrets: inherit